image: docker:latest

variables:
  IMAGE: $CI_REGISTRY_IMAGE
  NAME: $CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE:$NAME .
    - docker tag $IMAGE:$NAME
    - docker push $IMAGE:$NAME
