name: container
on:
  push:
    branches: [ main, devel ]
  pull_request:
  schedule:
    - cron: "42 02 * * 0"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ github.repository_owner }}/fpm:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64,linux/ppc64le
          push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
